apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic-architecture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolithic-architecture
  template:
    metadata:
      labels:
        app: monolithic-architecture
    spec:
      containers:
      - name: monolithic-container
        image: sundaydied/monolithic_architecture:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
