apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic-architecture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolithic-architecture
  template:
    metadata:
      labels:
        app: monolithic-architecture
    spec:
      containers:
      - name: monolithic-container
        image: sundaydied/monolithic_architecture:latest
        resources:
          requests:
            cpu: "100m"  
          limits:
            cpu: "2000m" 
        ports:
        - containerPort: 3000
