apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic-architecture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolithic-architecture
  template:
    metadata:
      labels:
        app: monolithic-architecture
    spec:
      containers:
      - name: monolithic-container
        image: sundaydied/monolithic_architecture:latest
        resources:
          requests:
            cpu: "25m"    # Requesting 200 milliCPU
            memory: "32Mi" # Requesting 256 MiB of memory
          limits:
            cpu: "500m"    # Limiting to 500 milliCPU
            memory: "256Mi" # Limiting to 512 MiB of memory
        ports:
        - containerPort: 3000
