apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-server
  template:
    metadata:
      labels:
        app: proxy-server
    spec:
      containers:
      - name: proxy-server
        image: sundaydied/microservices-architecture:proxy-server
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-server
spec:
  selector:
    app: proxy-server
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
