apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: sundaydied/microservices-architecture:service-b
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  ports:
  - port: 3002
    targetPort: 3002
  selector:
    app: service-b
